### PR TITLE
feature/add-gmail 

### PR DESCRIPTION
**Pull request by jvargas98**
## Explain why this change is being made.
because the application needs to send emails, then the gmail service will be used

### CODE REVIEW

**Review by ese-varo — APPROVED** [review]
Great job @jvargas98  :rocket:

**Review by GregVaz — APPROVED** [review]
:rocket:

**Review by LoginALee — APPROVED** [review]
Good work Jorge :rocket: !

**Review by OmauryMarmolejo — APPROVED** [review]
Great job!

**Pull request merged**
